# Generated by Django 2.1 on 2019-01-22 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Clent name')),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('on_way', 'On way'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='new', max_length=20, verbose_name='Status')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered', to=settings.AUTH_USER_MODEL, verbose_name='Courier')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Quantity')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='order.Food', verbose_name='Food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='order.Order', verbose_name='Order')),
            ],
        ),
    ]
